import Foundation

struct TurkishCities {
    static let cities: [String: [String]] = [
        "adana": ["seyhan", "yuregir", "cukurova", "saricam", "aladag", "ceyhan", "feke", "imamoglu", "karaisali", "karatas", "kozan", "pozanti", "saimbeyli", "tufanbeyli", "yumurtalik"],
        "adiyaman": ["merkez", "besni", "celikhan", "gerger", "golbasi", "kahta", "samsat", "sincik", "tut"],
        "afyonkarahisar": ["merkez", "basmakci", "bayat", "bolvadin", "cay", "cobanlar", "dazkiri", "dinar", "emirdag", "evciler", "hocalar", "ihsaniye", "iscehisar", "kiziloren", "sandikli", "sincanu", "sultandagi", "suhut"],
        "agri": ["merkez", "diyadin", "dogubeyazit", "eleskirt", "hamur", "patnos", "taslicay", "tutak"],
        "aksaray": ["merkez", "agacoren", "eskil", "gulagac", "guzelyurt", "ortakoy", "sariyahsi"],
        "amasya": ["merkez", "goynucek", "gumushacikoy", "hamamozu", "merzifon", "suluova", "tasova"],
        "ankara": ["altindag", "ayas", "bala", "beypazari", "camlidere", "cankaya", "cubuk", "elmadag", "etimesgut", "evren", "golbasi", "gudul", "haymana", "kalecik", "kahramankazan", "kecioren", "kizilcahamam", "mamak", "nallihan", "polatli", "pursaklar", "sincan", "sereflikochisar", "yenimahalle"],
        "antalya": ["akseki", "aksu", "alanya", "demre", "dosemealty", "elmali", "finike", "gazipasa", "gundogmus", "ibradi", "kale", "kas", "kemer", "kepez", "korkuteli", "konyaalti", "kumluca", "manavgat", "muratpasa", "serik"],
        "ardahan": ["merkez", "cildir", "damal", "gole", "hanak", "posof"],
        "artvin": ["merkez", "ardanuc", "arhavi", "borcka", "hopa", "murgul", "savsat", "yusufeli"],
        "aydin": ["bozdogan", "buharkent", "cine", "didim", "efeler", "germencik", "incirliova", "karacasu", "karpuzlu", "kocarli", "kuyucak", "kusadasi", "kuyucak", "nazilli", "soke", "sultanhisar", "yenipazar"],
        "balikesir": ["altieylul", "ayvalik", "balya", "bandirma", "bigadic", "burhaniye", "dursunbey", "edremit", "erdek", "gomec", "havran", "ivrindi", "karesi", "kepsut", "manyas", "marmara", "savastepe", "sindirgi", "susurluk"],
        "bartin": ["merkez", "amasra", "kurucasile", "ulus"],
        "batman": ["merkez", "besiri", "gercus", "hasankeyf", "kozluk", "sason"],
        "bayburt": ["merkez", "aydintepe", "demirozu"],
        "bilecik": ["merkez", "bozuyuk", "golpazari", "inhisar", "osmaneli", "pazaryeri", "sogut", "yenipazar"],
        "bingol": ["merkez", "adakli", "genc", "karliova", "kigi", "solhan", "yayladere", "yedisu"],
        "bitlis": ["merkez", "adilcevaz", "ahlat", "guroymak", "hizan", "mutki", "tatvan"],
        "bolu": ["merkez", "doртdivan", "gerede", "goynuk", "kibriscik", "mengen", "mudurnu", "seben", "yeniçaga"],
        "burdur": ["merkez", "aglasun", "altinyayla", "bucak", "cavdir", "celtikci", "golhisar", "karamanli", "kemer", "tefenni", "yesilova"],
        "bursa": ["gemlik", "gursu", "inegol", "iskele", "karacabey", "keles", "mudanya", "mustafakemalpasa", "nilufer", "orhaneli", "orhangazi", "osmangazi", "yenisehir", "yildirim"],
        "canakkale": ["ayvacik", "bayramic", "biga", "bozcaada", "can", "eceabat", "ezine", "gelibolu", "gokceada", "lapseki", "merkez", "yenice"],
        "cankiri": ["merkez", "atkaracalar", "bayramoren", "cerkes", "eldivan", "ilgaz", "kizilirmak", "korgun", "kursunlu", "orta", "sabanozu", "yaprakli"],
        "corum": ["alaca", "bayat", "bogazkale", "dodurga", "iskilip", "kargi", "lacin", "mecitozu", "merkez", "oguzlar", "ortakoy", "osmancik", "sungurlu", "ugurludag"],
        "denizli": ["acipayam", "akkoy", "babadag", "baklan", "bekcili", "beyagac", "bozkurt", "buldan", "cal", "cardak", "civril", "guney", "honaz", "kale", "merkezefendi", "pamukkale", "saraykoy", "serinhisar", "tavas"],
        "diyarbakir": ["baglar", "bismil", "cermik", "cinar", "cungus", "dicle", "egil", "ergani", "hani", "hazro", "kayapinar", "kocakoy", "kulp", "lice", "silvan", "sur", "yenisehir"],
        "duzce": ["akcakoca", "cumayeri", "cilimli", "golyaka", "gumusova", "kaynaşli", "merkez", "yigilca"],
        "edirne": ["enez", "havsa", "ipsala", "kesan", "lalapasa", "meric", "merkez", "suloglu", "uzunkopru"],
        "elazig": ["agin", "alacakaya", "aricak", "baskil", "karakocan", "keban", "kovancilar", "maden", "merkez", "palu", "sivrice"],
        "erzincan": ["cayirli", "ilic", "kemah", "kemaliye", "merkez", "otlukbeli", "refahiye", "tercan", "uzumlu"],
        "erzurum": ["askale", "aziziye", "cat", "hinis", "horasan", "ispir", "karacoban", "karayazi", "koprukoy", "narman", "oltu", "olur", "palandoken", "pasinler", "pazaryolu", "senkaya", "tekman", "tortum", "uzundere", "yakutiye"],
        "eskisehir": ["alpu", "beylikova", "cifteler", "gunyuzu", "han", "inonu", "mahmudiye", "mihalgazi", "mihalic", "odunpazari", "saricakaya", "seyitgazi", "sivrihisar", "tepebasi"],
        "gaziantep": ["araban", "islahiye", "karkamis", "nizip", "nurdagi", "oguzeli", "sahinbey", "sehitkamil", "yavuzeli"],
        "giresun": ["alucra", "bulancak", "camoluk", "canakci", "dereli", "dogankent", "espiye", "eynesil", "gorele", "guce", "keşap", "merkez", "piraziz", "sebinkarahisar", "tirebolu", "yaglideره"],
        "gumushane": ["merkez", "kelkit", "kose", "kurtun", "siran", "torul"],
        "hakkari": ["cukurca", "merkez", "semdinli", "yuksekova"],
        "hatay": ["altinozü", "arsuz", "belen", "defne", "dortyol", "erzin", "hassa", "iskenderun", "kirikhan", "kumlu", "payas", "reyhanli", "samandag", "yayladagi"],
        "igdir": ["aralik", "karakoyunlu", "merkez", "tuzluca"],
        "isparta": ["aksu", "atabey", "egirdir", "gelendost", "gonen", "keciborlu", "merkez", "senirkent", "sütçüler", "şarkikaraağaç", "uluborlu", "yalvaç", "yenisarbademli"],
        "istanbul": ["adalar", "arnavutkoy", "atasehir", "avcilar", "bagcilar", "bahcelievler", "bakirkoy", "basaksehir", "bayrampasa", "besiktas", "beykoz", "beylikduzu", "beyoglu", "buyukcekmece", "catalca", "cekmekoy", "esenler", "esenyurt", "eyupsultan", "fatih", "gaziosmanpasa", "gungoren", "kadikoy", "kagithane", "kartal", "kucukcekmece", "maltepe", "pendik", "sancaktepe", "sariyer", "silivri", "sultanbeyli", "sultangazi", "sisli", "sile", "tuzla", "umraniye", "uskudar", "zeytinburnu"],
        "izmir": ["aliaga", "balcova", "bayindir", "bayrakli", "bergama", "beydağ", "bornova", "buca", "cesme", "cigli", "dikili", "foca", "gaziemir", "guzelbahce", "karabaglar", "karaburun", "karşıyaka", "kemalpasa", "kinik", "kiraz", "konak", "menderes", "menemen", "narlidere", "odemis", "seferihisar", "selcuk", "tire", "torbali", "urla"],
        "kahramanmaras": ["afsin", "andirin", "caglayancerit", "dulkadiroglu", "ekinozu", "elbistan", "göksun", "nurhak", "onikisubat", "pazarcik", "turkoglu"],
        "karabuk": ["eflani", "eskipazar", "merkez", "ovacik", "safranbolu", "yenice"],
        "karaman": ["ayranci", "basyayla", "ermenek", "kazimkarabekir", "merkez", "sarıveliler"],
        "kars": ["akyaka", "arpaçay", "digor", "kagizman", "merkez", "sarikamis", "selim", "susuz"],
        "kastamonu": ["abana", "aglı", "araç", "azdavay", "bozkurt", "cide", "catalzeytin", "daday", "devrekani", "doğanyurt", "hanonu", "ihsangazi", "inebolu", "kure", "merkez", "pinarbasi", "seydiler", "şenpazar", "taskopru", "tosya"],
        "kayseri": ["cocoran", "develi", "felahiye", "hacilar", "incesu", "kocasinan", "melikgazi", "ozvatan", "pinarbasi", "sarioglan", "sariz", "talas", "tomarza", "yahyali", "yesilhisar"],
        "kilis": ["elbeyli", "merkez", "musabeyli", "polateli"],
        "kirikkale": ["bahsili", "baliseyh", "celebi", "delice", "karakeçili", "keskin", "merkez", "sulakyurt", "yahsihan"],
        "kirklareli": ["babaeski", "demirkoy", "kofcaz", "luleburgaz", "merkez", "pehlivankoy", "pinarhisar", "vize"],
        "kirsehir": ["akçakent", "akpinar", "boztepe", "cicekdagi", "kaman", "merkez", "mucur"],
        "kocaeli": ["basiskele", "cayırova", "darica", "derince", "dilovasi", "gebze", "golcuk", "izmit", "kandira", "karamursel", "kartepe", "korfez"],
        "konya": ["ahirli", "akoren", "aksehir", "altınekin", "beysehir", "bozkir", "çeltik", "cihanbeyli", "çumra", "derbent", "derebucak", "doganhisar", "emirgazi", "eregli", "guneysinir", "hadim", "halkapınar", "huyuk", "ilgin", "kadinhani", "karapinar", "karatay", "kulu", "meram", "sarayonu", "selcuklu", "seydisehir", "taskent", "tuzlukçu", "yalihüyük", "yunak"],
        "kutahya": ["altıntaş", "aslanapa", "cavdarhisar", "domanic", "dumlupinar", "emet", "gediz", "hisarcik", "merkez", "pazarlar", "saphane", "simav", "tavsanli"],
        "malatya": ["akcadag", "arapgir", "arguvan", "battalgazi", "darende", "dogansehir", "doganyol", "hekimhan", "kale", "kuluncak", "puturge", "yazihan", "yesilyurt"],
        "manisa": ["ahmetli", "akhisar", "alasehir", "demirci", "golmarmara", "gordes", "kirkagac", "koprubasi", "kula", "salihli", "sarigol", "saruhanli", "selendi", "soma", "sehzadeler", "turgutlu", "yunusemre"],
        "mardin": ["artuklu", "dargecit", "derik", "kiziltepe", "mazidagi", "midyat", "nusaybin", "omerli", "savur", "yesilli"],
        "mersin": ["anamur", "aydincik", "bozyazi", "camliyayla", "erdemli", "gülnar", "mezitli", "mut", "silifke", "tarsus", "toroslar", "yenisehir"],
        "mugla": ["bodrum", "dalaman", "datca", "fethiye", "kavaklidere", "koycegiz", "marmaris", "menteşe", "milas", "ortaca", "seydikemer", "ula", "yatagan"],
        "mus": ["bulanık", "haskoy", "korkut", "malazgirt", "merkez", "varto"],
        "nevsehir": ["acigol", "avanos", "derinkuyu", "gulsehir", "hacibektas", "kozakli", "merkez", "urgup"],
        "nigde": ["altunhisar", "bor", "camardi", "ciftlik", "merkez", "ulukisla"],
        "ordu": ["akkus", "altinordu", "aybasti", "camas", "catalpinar", "caybaşı", "fatsa", "golkoy", "gulyali", "gurgentepe", "ikizce", "kabaduz", "kabatas", "korgan", "kumru", "mesudiye", "persembe", "ulubey", "unye"],
        "osmaniye": ["bahce", "duzici", "hasanbeyli", "kadirli", "merkez", "sumbas", "toprakkale"],
        "rize": ["ardesen", "camlihemsin", "cayeli", "derepazari", "findikli", "guneysu", "hemsin", "ikizdere", "iyidere", "kalkandere", "merkez", "pazar"],
        "sakarya": ["adapazari", "akyazi", "arifiye", "erenler", "ferizli", "geyve", "hendek", "karapurcek", "karasu", "kaynarca", "kocaali", "pamukova", "sapanca", "serdivan", "sogutlu", "tarakli"],
        "samsun": ["alacam", "asarcik", "atakum", "ayvacik", "bafra", "canik", "carsamba", "havza", "ilkadim", "kavak", "ladik", "salipazari", "tekkekoy", "terme", "vezirkopru", "yakakent"],
        "sanliurfa": ["akcakale", "birecik", "bozova", "ceylanpinar", "eyyubiye", "halfeti", "haliliye", "harran", "hilvan", "karakopru", "siverek", "suruc", "viransehir"],
        "siirt": ["aydinlar", "baykan", "eruh", "kurtalan", "merkez", "pervari", "sirvan", "tillo"],
        "sinop": ["ayancik", "boyabat", "dikmen", "duragan", "erfelek", "gerze", "merkez", "sarayduzu", "turkeli"],
        "sivas": ["akincilar", "altinyayla", "divrigi", "doğanşar", "gemerek", "golova", "gurun", "hafik", "imranli", "kangal", "koyulhisar", "merkez", "susehri", "şarkisla", "ulas", "yildizeli", "zara"],
        "sirnak": ["beytussebap", "cizre", "guclukonak", "idil", "merkez", "silopi", "uludere"],
        "tekirdag": ["cerkezkoy", "corlu", "ergene", "hayrabolu", "kapakli", "malkara", "marmaraereglisi", "muratli", "saray", "sarkoy", "suleymanpasa"],
        "tokat": ["almus", "artova", "basciftlik", "erbaa", "merkez", "niksar", "pazar", "resadiye", "sulusaray", "turhal", "yesilyurt", "zile"],
        "trabzon": ["akcaabat", "arakli", "arsin", "besikduzu", "carsibasi", "caykara", "dernekpazari", "duzkoy", "hayrat", "koprubasi", "last", "macka", "of", "ortahisar", "surmene", "tonya", "vakfikebir", "yomra"],
        "tunceli": ["cemisgezek", "hozat", "mazgirt", "merkez", "nazimiye", "ovacik", "pertek", "pulumur"],
        "usak": ["banaz", "esme", "karahalli", "merkez", "sivasli", "ulubey"],
        "van": ["bahcesaray", "baskale", "caldiran", "catak", "edremit", "ercis", "gevas", "gurpinar", "ipekyolu", "muradiye", "ozalp", "saray", "tusba"],
        "yalova": ["altinova", "armutlu", "cinarcik", "ciftlikkoy", "merkez", "termal"],
        "yozgat": ["akdagmadeni", "aydincik", "bogazliyan", "candir", "cayiralan", "cekerek", "kadisehri", "merkez", "saraykent", "sarikaya", "sorgun", "sefaatli", "yenifakili", "yerköy"],
        "zonguldak": ["alaplı", "caycuma", "devrek", "eregli", "gokcebey", "kilimli", "kozlu", "merkez"]
    ]
    
    static let cityNames: [String] = Array(cities.keys).sorted()
    
    // Türkçe karakterleri temizle
    static func normalize(_ text: String) -> String {
        let mapping: [Character: String] = [
            "ç": "c", "ğ": "g", "ı": "i", "ö": "o", "ş": "s", "ü": "u",
            "Ç": "c", "Ğ": "g", "İ": "i", "Ö": "o", "Ş": "s", "Ü": "u"
        ]
        
        return text.lowercased().map { mapping[$0] ?? String($0) }.joined()
    }
}
